name: Build & Deploy MkDocs

on:
  push:
    branches: [ main ]          # change if your default branch is different
  workflow_dispatch:            # lets you trigger it manually

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repo
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0        # mkdocs needs full history for versioning

      # 2 Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3 Install MkDocs & theme
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material            # + any plugins you use

      # 4 Build the docs into site/
      - name: Build documentation
        run: mkdocs build --strict --verbose

      # 5 Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site            # mkdocs outputs here
          publish_branch: gh-pages       # default is gh-pages
          force_orphan: true             # keeps history small
